//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  site: Site;
  siteConnection: SiteConnection;
  event: Event;
  eventConnection: EventConnection;
  division: Division;
  divisionConnection: DivisionConnection;
  resource: Resource;
  resourceConnection: ResourceConnection;
  announcements: Announcements;
  announcementsConnection: AnnouncementsConnection;
  popeIntention: PopeIntention;
  popeIntentionConnection: PopeIntentionConnection;
  gallery: Gallery;
  galleryConnection: GalleryConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
};


export type QueryEventArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventFilter>;
};


export type QueryDivisionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDivisionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DivisionFilter>;
};


export type QueryResourceArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryResourceConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResourceFilter>;
};


export type QueryAnnouncementsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAnnouncementsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AnnouncementsFilter>;
};


export type QueryPopeIntentionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPopeIntentionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PopeIntentionFilter>;
};


export type QueryGalleryArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryGalleryConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GalleryFilter>;
};

export type DocumentFilter = {
  site?: InputMaybe<SiteFilter>;
  event?: InputMaybe<EventFilter>;
  division?: InputMaybe<DivisionFilter>;
  resource?: InputMaybe<ResourceFilter>;
  announcements?: InputMaybe<AnnouncementsFilter>;
  popeIntention?: InputMaybe<PopeIntentionFilter>;
  gallery?: InputMaybe<GalleryFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Site | Event | Division | Resource | Announcements | PopeIntention | Gallery | Folder;

export type SiteHero = {
  __typename?: 'SiteHero';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  caption?: Maybe<Scalars['String']['output']>;
};

export type SiteAbout = {
  __typename?: 'SiteAbout';
  headline?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type SiteDivisionIntro = {
  __typename?: 'SiteDivisionIntro';
  headline?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type SiteEventIntro = {
  __typename?: 'SiteEventIntro';
  headline?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type SiteJoin = {
  __typename?: 'SiteJoin';
  headline?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type Site = Node & Document & {
  __typename?: 'Site';
  hero?: Maybe<SiteHero>;
  about?: Maybe<SiteAbout>;
  divisionIntro?: Maybe<SiteDivisionIntro>;
  eventIntro?: Maybe<SiteEventIntro>;
  join?: Maybe<SiteJoin>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteHeroFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  caption?: InputMaybe<StringFilter>;
};

export type SiteAboutFilter = {
  headline?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type SiteDivisionIntroFilter = {
  headline?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type SiteEventIntroFilter = {
  headline?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type SiteJoinFilter = {
  headline?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type SiteFilter = {
  hero?: InputMaybe<SiteHeroFilter>;
  about?: InputMaybe<SiteAboutFilter>;
  divisionIntro?: InputMaybe<SiteDivisionIntroFilter>;
  eventIntro?: InputMaybe<SiteEventIntroFilter>;
  join?: InputMaybe<SiteJoinFilter>;
};

export type SiteConnectionEdges = {
  __typename?: 'SiteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Site>;
};

export type SiteConnection = Connection & {
  __typename?: 'SiteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteConnectionEdges>>>;
};

export type Event = Node & Document & {
  __typename?: 'Event';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  type: Scalars['String']['output'];
  description: Scalars['String']['output'];
  image?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type EventFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  type?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type EventConnectionEdges = {
  __typename?: 'EventConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Event>;
};

export type EventConnection = Connection & {
  __typename?: 'EventConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EventConnectionEdges>>>;
};

export type Division = Node & Document & {
  __typename?: 'Division';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  color: Scalars['String']['output'];
  motto?: Maybe<Scalars['String']['output']>;
  description: Scalars['String']['output'];
  details?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DivisionFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
  motto?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  details?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type DivisionConnectionEdges = {
  __typename?: 'DivisionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Division>;
};

export type DivisionConnection = Connection & {
  __typename?: 'DivisionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DivisionConnectionEdges>>>;
};

export type Resource = Node & Document & {
  __typename?: 'Resource';
  title: Scalars['String']['output'];
  category: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  externalUrl?: Maybe<Scalars['String']['output']>;
  file?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ResourceFilter = {
  title?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  externalUrl?: InputMaybe<StringFilter>;
  file?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ResourceConnectionEdges = {
  __typename?: 'ResourceConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Resource>;
};

export type ResourceConnection = Connection & {
  __typename?: 'ResourceConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ResourceConnectionEdges>>>;
};

export type AnnouncementsItems = {
  __typename?: 'AnnouncementsItems';
  title: Scalars['String']['output'];
  message: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  pinned?: Maybe<Scalars['Boolean']['output']>;
};

export type Announcements = Node & Document & {
  __typename?: 'Announcements';
  items?: Maybe<Array<Maybe<AnnouncementsItems>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type AnnouncementsItemsFilter = {
  title?: InputMaybe<StringFilter>;
  message?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  pinned?: InputMaybe<BooleanFilter>;
};

export type AnnouncementsFilter = {
  items?: InputMaybe<AnnouncementsItemsFilter>;
};

export type AnnouncementsConnectionEdges = {
  __typename?: 'AnnouncementsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Announcements>;
};

export type AnnouncementsConnection = Connection & {
  __typename?: 'AnnouncementsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AnnouncementsConnectionEdges>>>;
};

export type PopeIntention = Node & Document & {
  __typename?: 'PopeIntention';
  month: Scalars['String']['output'];
  title: Scalars['String']['output'];
  text: Scalars['String']['output'];
  source?: Maybe<Scalars['String']['output']>;
  sourceUrl?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PopeIntentionFilter = {
  month?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  source?: InputMaybe<StringFilter>;
  sourceUrl?: InputMaybe<StringFilter>;
};

export type PopeIntentionConnectionEdges = {
  __typename?: 'PopeIntentionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<PopeIntention>;
};

export type PopeIntentionConnection = Connection & {
  __typename?: 'PopeIntentionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PopeIntentionConnectionEdges>>>;
};

export type GalleryPosts = {
  __typename?: 'GalleryPosts';
  url?: Maybe<Scalars['String']['output']>;
  caption?: Maybe<Scalars['String']['output']>;
};

export type Gallery = Node & Document & {
  __typename?: 'Gallery';
  instagramHandle?: Maybe<Scalars['String']['output']>;
  posts?: Maybe<Array<Maybe<GalleryPosts>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type GalleryPostsFilter = {
  url?: InputMaybe<StringFilter>;
  caption?: InputMaybe<StringFilter>;
};

export type GalleryFilter = {
  instagramHandle?: InputMaybe<StringFilter>;
  posts?: InputMaybe<GalleryPostsFilter>;
};

export type GalleryConnectionEdges = {
  __typename?: 'GalleryConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Gallery>;
};

export type GalleryConnection = Connection & {
  __typename?: 'GalleryConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<GalleryConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateSite: Site;
  createSite: Site;
  updateEvent: Event;
  createEvent: Event;
  updateDivision: Division;
  createDivision: Division;
  updateResource: Resource;
  createResource: Resource;
  updateAnnouncements: Announcements;
  createAnnouncements: Announcements;
  updatePopeIntention: PopeIntention;
  createPopeIntention: PopeIntention;
  updateGallery: Gallery;
  createGallery: Gallery;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationCreateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationUpdateEventArgs = {
  relativePath: Scalars['String']['input'];
  params: EventMutation;
};


export type MutationCreateEventArgs = {
  relativePath: Scalars['String']['input'];
  params: EventMutation;
};


export type MutationUpdateDivisionArgs = {
  relativePath: Scalars['String']['input'];
  params: DivisionMutation;
};


export type MutationCreateDivisionArgs = {
  relativePath: Scalars['String']['input'];
  params: DivisionMutation;
};


export type MutationUpdateResourceArgs = {
  relativePath: Scalars['String']['input'];
  params: ResourceMutation;
};


export type MutationCreateResourceArgs = {
  relativePath: Scalars['String']['input'];
  params: ResourceMutation;
};


export type MutationUpdateAnnouncementsArgs = {
  relativePath: Scalars['String']['input'];
  params: AnnouncementsMutation;
};


export type MutationCreateAnnouncementsArgs = {
  relativePath: Scalars['String']['input'];
  params: AnnouncementsMutation;
};


export type MutationUpdatePopeIntentionArgs = {
  relativePath: Scalars['String']['input'];
  params: PopeIntentionMutation;
};


export type MutationCreatePopeIntentionArgs = {
  relativePath: Scalars['String']['input'];
  params: PopeIntentionMutation;
};


export type MutationUpdateGalleryArgs = {
  relativePath: Scalars['String']['input'];
  params: GalleryMutation;
};


export type MutationCreateGalleryArgs = {
  relativePath: Scalars['String']['input'];
  params: GalleryMutation;
};

export type DocumentUpdateMutation = {
  site?: InputMaybe<SiteMutation>;
  event?: InputMaybe<EventMutation>;
  division?: InputMaybe<DivisionMutation>;
  resource?: InputMaybe<ResourceMutation>;
  announcements?: InputMaybe<AnnouncementsMutation>;
  popeIntention?: InputMaybe<PopeIntentionMutation>;
  gallery?: InputMaybe<GalleryMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  site?: InputMaybe<SiteMutation>;
  event?: InputMaybe<EventMutation>;
  division?: InputMaybe<DivisionMutation>;
  resource?: InputMaybe<ResourceMutation>;
  announcements?: InputMaybe<AnnouncementsMutation>;
  popeIntention?: InputMaybe<PopeIntentionMutation>;
  gallery?: InputMaybe<GalleryMutation>;
};

export type SiteHeroMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  caption?: InputMaybe<Scalars['String']['input']>;
};

export type SiteAboutMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type SiteDivisionIntroMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type SiteEventIntroMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type SiteJoinMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type SiteMutation = {
  hero?: InputMaybe<SiteHeroMutation>;
  about?: InputMaybe<SiteAboutMutation>;
  divisionIntro?: InputMaybe<SiteDivisionIntroMutation>;
  eventIntro?: InputMaybe<SiteEventIntroMutation>;
  join?: InputMaybe<SiteJoinMutation>;
};

export type EventMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type DivisionMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  color?: InputMaybe<Scalars['String']['input']>;
  motto?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  details?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ResourceMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  externalUrl?: InputMaybe<Scalars['String']['input']>;
  file?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type AnnouncementsItemsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  message?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  pinned?: InputMaybe<Scalars['Boolean']['input']>;
};

export type AnnouncementsMutation = {
  items?: InputMaybe<Array<InputMaybe<AnnouncementsItemsMutation>>>;
};

export type PopeIntentionMutation = {
  month?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  source?: InputMaybe<Scalars['String']['input']>;
  sourceUrl?: InputMaybe<Scalars['String']['input']>;
};

export type GalleryPostsMutation = {
  url?: InputMaybe<Scalars['String']['input']>;
  caption?: InputMaybe<Scalars['String']['input']>;
};

export type GalleryMutation = {
  instagramHandle?: InputMaybe<Scalars['String']['input']>;
  posts?: InputMaybe<Array<InputMaybe<GalleryPostsMutation>>>;
};

export type SitePartsFragment = { __typename: 'Site', hero?: { __typename: 'SiteHero', eyebrow?: string | null, title?: string | null, subtitle?: string | null, caption?: string | null } | null, about?: { __typename: 'SiteAbout', headline?: string | null, description?: string | null } | null, divisionIntro?: { __typename: 'SiteDivisionIntro', headline?: string | null, description?: string | null } | null, eventIntro?: { __typename: 'SiteEventIntro', headline?: string | null, description?: string | null } | null, join?: { __typename: 'SiteJoin', headline?: string | null, description?: string | null } | null };

export type EventPartsFragment = { __typename: 'Event', title: string, date: string, type: string, description: string, image?: string | null, body?: any | null };

export type DivisionPartsFragment = { __typename: 'Division', title: string, subtitle?: string | null, color: string, motto?: string | null, description: string, details?: string | null, image?: string | null, body?: any | null };

export type ResourcePartsFragment = { __typename: 'Resource', title: string, category: string, description?: string | null, externalUrl?: string | null, file?: string | null, body?: any | null };

export type AnnouncementsPartsFragment = { __typename: 'Announcements', items?: Array<{ __typename: 'AnnouncementsItems', title: string, message: string, date?: string | null, pinned?: boolean | null } | null> | null };

export type PopeIntentionPartsFragment = { __typename: 'PopeIntention', month: string, title: string, text: string, source?: string | null, sourceUrl?: string | null };

export type GalleryPartsFragment = { __typename: 'Gallery', instagramHandle?: string | null, posts?: Array<{ __typename: 'GalleryPosts', url?: string | null, caption?: string | null } | null> | null };

export type SiteQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteQuery = { __typename?: 'Query', site: { __typename: 'Site', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'SiteHero', eyebrow?: string | null, title?: string | null, subtitle?: string | null, caption?: string | null } | null, about?: { __typename: 'SiteAbout', headline?: string | null, description?: string | null } | null, divisionIntro?: { __typename: 'SiteDivisionIntro', headline?: string | null, description?: string | null } | null, eventIntro?: { __typename: 'SiteEventIntro', headline?: string | null, description?: string | null } | null, join?: { __typename: 'SiteJoin', headline?: string | null, description?: string | null } | null } };

export type SiteConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
}>;


export type SiteConnectionQuery = { __typename?: 'Query', siteConnection: { __typename?: 'SiteConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteConnectionEdges', cursor: string, node?: { __typename: 'Site', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'SiteHero', eyebrow?: string | null, title?: string | null, subtitle?: string | null, caption?: string | null } | null, about?: { __typename: 'SiteAbout', headline?: string | null, description?: string | null } | null, divisionIntro?: { __typename: 'SiteDivisionIntro', headline?: string | null, description?: string | null } | null, eventIntro?: { __typename: 'SiteEventIntro', headline?: string | null, description?: string | null } | null, join?: { __typename: 'SiteJoin', headline?: string | null, description?: string | null } | null } | null } | null> | null } };

export type EventQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EventQuery = { __typename?: 'Query', event: { __typename: 'Event', id: string, title: string, date: string, type: string, description: string, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EventConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventFilter>;
}>;


export type EventConnectionQuery = { __typename?: 'Query', eventConnection: { __typename?: 'EventConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EventConnectionEdges', cursor: string, node?: { __typename: 'Event', id: string, title: string, date: string, type: string, description: string, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type DivisionQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DivisionQuery = { __typename?: 'Query', division: { __typename: 'Division', id: string, title: string, subtitle?: string | null, color: string, motto?: string | null, description: string, details?: string | null, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type DivisionConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DivisionFilter>;
}>;


export type DivisionConnectionQuery = { __typename?: 'Query', divisionConnection: { __typename?: 'DivisionConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DivisionConnectionEdges', cursor: string, node?: { __typename: 'Division', id: string, title: string, subtitle?: string | null, color: string, motto?: string | null, description: string, details?: string | null, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ResourceQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ResourceQuery = { __typename?: 'Query', resource: { __typename: 'Resource', id: string, title: string, category: string, description?: string | null, externalUrl?: string | null, file?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ResourceConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ResourceFilter>;
}>;


export type ResourceConnectionQuery = { __typename?: 'Query', resourceConnection: { __typename?: 'ResourceConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ResourceConnectionEdges', cursor: string, node?: { __typename: 'Resource', id: string, title: string, category: string, description?: string | null, externalUrl?: string | null, file?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type AnnouncementsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AnnouncementsQuery = { __typename?: 'Query', announcements: { __typename: 'Announcements', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'AnnouncementsItems', title: string, message: string, date?: string | null, pinned?: boolean | null } | null> | null } };

export type AnnouncementsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AnnouncementsFilter>;
}>;


export type AnnouncementsConnectionQuery = { __typename?: 'Query', announcementsConnection: { __typename?: 'AnnouncementsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AnnouncementsConnectionEdges', cursor: string, node?: { __typename: 'Announcements', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, items?: Array<{ __typename: 'AnnouncementsItems', title: string, message: string, date?: string | null, pinned?: boolean | null } | null> | null } | null } | null> | null } };

export type PopeIntentionQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PopeIntentionQuery = { __typename?: 'Query', popeIntention: { __typename: 'PopeIntention', id: string, month: string, title: string, text: string, source?: string | null, sourceUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PopeIntentionConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PopeIntentionFilter>;
}>;


export type PopeIntentionConnectionQuery = { __typename?: 'Query', popeIntentionConnection: { __typename?: 'PopeIntentionConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PopeIntentionConnectionEdges', cursor: string, node?: { __typename: 'PopeIntention', id: string, month: string, title: string, text: string, source?: string | null, sourceUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type GalleryQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type GalleryQuery = { __typename?: 'Query', gallery: { __typename: 'Gallery', id: string, instagramHandle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, posts?: Array<{ __typename: 'GalleryPosts', url?: string | null, caption?: string | null } | null> | null } };

export type GalleryConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<GalleryFilter>;
}>;


export type GalleryConnectionQuery = { __typename?: 'Query', galleryConnection: { __typename?: 'GalleryConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'GalleryConnectionEdges', cursor: string, node?: { __typename: 'Gallery', id: string, instagramHandle?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, posts?: Array<{ __typename: 'GalleryPosts', url?: string | null, caption?: string | null } | null> | null } | null } | null> | null } };

export const SitePartsFragmentDoc = gql`
    fragment SiteParts on Site {
  __typename
  hero {
    __typename
    eyebrow
    title
    subtitle
    caption
  }
  about {
    __typename
    headline
    description
  }
  divisionIntro {
    __typename
    headline
    description
  }
  eventIntro {
    __typename
    headline
    description
  }
  join {
    __typename
    headline
    description
  }
}
    `;
export const EventPartsFragmentDoc = gql`
    fragment EventParts on Event {
  __typename
  title
  date
  type
  description
  image
  body
}
    `;
export const DivisionPartsFragmentDoc = gql`
    fragment DivisionParts on Division {
  __typename
  title
  subtitle
  color
  motto
  description
  details
  image
  body
}
    `;
export const ResourcePartsFragmentDoc = gql`
    fragment ResourceParts on Resource {
  __typename
  title
  category
  description
  externalUrl
  file
  body
}
    `;
export const AnnouncementsPartsFragmentDoc = gql`
    fragment AnnouncementsParts on Announcements {
  __typename
  items {
    __typename
    title
    message
    date
    pinned
  }
}
    `;
export const PopeIntentionPartsFragmentDoc = gql`
    fragment PopeIntentionParts on PopeIntention {
  __typename
  month
  title
  text
  source
  sourceUrl
}
    `;
export const GalleryPartsFragmentDoc = gql`
    fragment GalleryParts on Gallery {
  __typename
  instagramHandle
  posts {
    __typename
    url
    caption
  }
}
    `;
export const SiteDocument = gql`
    query site($relativePath: String!) {
  site(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteParts
  }
}
    ${SitePartsFragmentDoc}`;
export const SiteConnectionDocument = gql`
    query siteConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteFilter) {
  siteConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteParts
      }
    }
  }
}
    ${SitePartsFragmentDoc}`;
export const EventDocument = gql`
    query event($relativePath: String!) {
  event(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventParts
  }
}
    ${EventPartsFragmentDoc}`;
export const EventConnectionDocument = gql`
    query eventConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventFilter) {
  eventConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventParts
      }
    }
  }
}
    ${EventPartsFragmentDoc}`;
export const DivisionDocument = gql`
    query division($relativePath: String!) {
  division(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DivisionParts
  }
}
    ${DivisionPartsFragmentDoc}`;
export const DivisionConnectionDocument = gql`
    query divisionConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DivisionFilter) {
  divisionConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DivisionParts
      }
    }
  }
}
    ${DivisionPartsFragmentDoc}`;
export const ResourceDocument = gql`
    query resource($relativePath: String!) {
  resource(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ResourceParts
  }
}
    ${ResourcePartsFragmentDoc}`;
export const ResourceConnectionDocument = gql`
    query resourceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ResourceFilter) {
  resourceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ResourceParts
      }
    }
  }
}
    ${ResourcePartsFragmentDoc}`;
export const AnnouncementsDocument = gql`
    query announcements($relativePath: String!) {
  announcements(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AnnouncementsParts
  }
}
    ${AnnouncementsPartsFragmentDoc}`;
export const AnnouncementsConnectionDocument = gql`
    query announcementsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AnnouncementsFilter) {
  announcementsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AnnouncementsParts
      }
    }
  }
}
    ${AnnouncementsPartsFragmentDoc}`;
export const PopeIntentionDocument = gql`
    query popeIntention($relativePath: String!) {
  popeIntention(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PopeIntentionParts
  }
}
    ${PopeIntentionPartsFragmentDoc}`;
export const PopeIntentionConnectionDocument = gql`
    query popeIntentionConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PopeIntentionFilter) {
  popeIntentionConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PopeIntentionParts
      }
    }
  }
}
    ${PopeIntentionPartsFragmentDoc}`;
export const GalleryDocument = gql`
    query gallery($relativePath: String!) {
  gallery(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...GalleryParts
  }
}
    ${GalleryPartsFragmentDoc}`;
export const GalleryConnectionDocument = gql`
    query galleryConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: GalleryFilter) {
  galleryConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...GalleryParts
      }
    }
  }
}
    ${GalleryPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      site(variables: SiteQueryVariables, options?: C): Promise<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}> {
        return requester<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}, SiteQueryVariables>(SiteDocument, variables, options);
      },
    siteConnection(variables?: SiteConnectionQueryVariables, options?: C): Promise<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}> {
        return requester<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}, SiteConnectionQueryVariables>(SiteConnectionDocument, variables, options);
      },
    event(variables: EventQueryVariables, options?: C): Promise<{data: EventQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventQueryVariables, query: string}> {
        return requester<{data: EventQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventQueryVariables, query: string}, EventQueryVariables>(EventDocument, variables, options);
      },
    eventConnection(variables?: EventConnectionQueryVariables, options?: C): Promise<{data: EventConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventConnectionQueryVariables, query: string}> {
        return requester<{data: EventConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventConnectionQueryVariables, query: string}, EventConnectionQueryVariables>(EventConnectionDocument, variables, options);
      },
    division(variables: DivisionQueryVariables, options?: C): Promise<{data: DivisionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DivisionQueryVariables, query: string}> {
        return requester<{data: DivisionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DivisionQueryVariables, query: string}, DivisionQueryVariables>(DivisionDocument, variables, options);
      },
    divisionConnection(variables?: DivisionConnectionQueryVariables, options?: C): Promise<{data: DivisionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DivisionConnectionQueryVariables, query: string}> {
        return requester<{data: DivisionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DivisionConnectionQueryVariables, query: string}, DivisionConnectionQueryVariables>(DivisionConnectionDocument, variables, options);
      },
    resource(variables: ResourceQueryVariables, options?: C): Promise<{data: ResourceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourceQueryVariables, query: string}> {
        return requester<{data: ResourceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourceQueryVariables, query: string}, ResourceQueryVariables>(ResourceDocument, variables, options);
      },
    resourceConnection(variables?: ResourceConnectionQueryVariables, options?: C): Promise<{data: ResourceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourceConnectionQueryVariables, query: string}> {
        return requester<{data: ResourceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ResourceConnectionQueryVariables, query: string}, ResourceConnectionQueryVariables>(ResourceConnectionDocument, variables, options);
      },
    announcements(variables: AnnouncementsQueryVariables, options?: C): Promise<{data: AnnouncementsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AnnouncementsQueryVariables, query: string}> {
        return requester<{data: AnnouncementsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AnnouncementsQueryVariables, query: string}, AnnouncementsQueryVariables>(AnnouncementsDocument, variables, options);
      },
    announcementsConnection(variables?: AnnouncementsConnectionQueryVariables, options?: C): Promise<{data: AnnouncementsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AnnouncementsConnectionQueryVariables, query: string}> {
        return requester<{data: AnnouncementsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AnnouncementsConnectionQueryVariables, query: string}, AnnouncementsConnectionQueryVariables>(AnnouncementsConnectionDocument, variables, options);
      },
    popeIntention(variables: PopeIntentionQueryVariables, options?: C): Promise<{data: PopeIntentionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PopeIntentionQueryVariables, query: string}> {
        return requester<{data: PopeIntentionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PopeIntentionQueryVariables, query: string}, PopeIntentionQueryVariables>(PopeIntentionDocument, variables, options);
      },
    popeIntentionConnection(variables?: PopeIntentionConnectionQueryVariables, options?: C): Promise<{data: PopeIntentionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PopeIntentionConnectionQueryVariables, query: string}> {
        return requester<{data: PopeIntentionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PopeIntentionConnectionQueryVariables, query: string}, PopeIntentionConnectionQueryVariables>(PopeIntentionConnectionDocument, variables, options);
      },
    gallery(variables: GalleryQueryVariables, options?: C): Promise<{data: GalleryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryQueryVariables, query: string}> {
        return requester<{data: GalleryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryQueryVariables, query: string}, GalleryQueryVariables>(GalleryDocument, variables, options);
      },
    galleryConnection(variables?: GalleryConnectionQueryVariables, options?: C): Promise<{data: GalleryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryConnectionQueryVariables, query: string}> {
        return requester<{data: GalleryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: GalleryConnectionQueryVariables, query: string}, GalleryConnectionQueryVariables>(GalleryConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  